# Generated by Django 4.1.6 on 2023-03-06 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_term', models.CharField(choices=[('1st', 'First'), ('2nd', 'Second'), ('3rd', 'Third')], max_length=3, verbose_name='Exam Term')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Class Name')),
                ('number_of_students', models.IntegerField()),
                ('classteacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Class Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('date_of_birth', models.DateField(verbose_name='Date Of Birth')),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('student_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StudentExamReport.grade', verbose_name="Student's Class")),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Subject Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Subject Code')),
                ('marks', models.IntegerField(verbose_name='Subjects Mark')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentExamReport.grade', verbose_name='Subjects Grade')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentExamReport.student', verbose_name="Student's Name")),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentExamReport.subject', verbose_name="Student's Subject")),
            ],
        ),
        migrations.CreateModel(
            name='ResultComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_comment', models.CharField(max_length=300)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentExamReport.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentExamReport.student')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('teachers_comment', models.CharField(max_length=300, verbose_name="Teacher's Comment")),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentExamReport.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentExamReport.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentExamReport.subject')),
            ],
        ),
    ]
